/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.JournalData;
import jooq.tables.records.JournalDataRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JournalDataRecord> PK_JOURNAL_DATA = Internal.createUniqueKey(JournalData.JOURNAL_DATA, DSL.name("pk_journal_data"), new TableField[] { JournalData.JOURNAL_DATA.NOTE_ID }, true);
    public static final UniqueKey<JournalDataRecord> SQLITE_AUTOINDEX_JOURNAL_DATA_1 = Internal.createUniqueKey(JournalData.JOURNAL_DATA, DSL.name("sqlite_autoindex_journal_data_1"), new TableField[] { JournalData.JOURNAL_DATA.NOTE_ID }, true);
    public static final UniqueKey<JournalDataRecord> SQLITE_AUTOINDEX_JOURNAL_DATA_2 = Internal.createUniqueKey(JournalData.JOURNAL_DATA, DSL.name("sqlite_autoindex_journal_data_2"), new TableField[] { JournalData.JOURNAL_DATA.DATE }, true);
}
