/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.JournalData;
import jooq.tables.SqliteSequence;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>journal_data</code>.
     */
    public static final JournalData JOURNAL_DATA = JournalData.JOURNAL_DATA;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;
}
