/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.JournalData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JournalDataRecord extends UpdatableRecordImpl<JournalDataRecord> implements Record8<Integer, String, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>journal_data.note_id</code>.
     */
    public void setNoteId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>journal_data.note_id</code>.
     */
    public Integer getNoteId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>journal_data.date</code>.
     */
    public void setDate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>journal_data.date</code>.
     */
    public String getDate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>journal_data.day</code>.
     */
    public void setDay(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>journal_data.day</code>.
     */
    public Integer getDay() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>journal_data.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>journal_data.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>journal_data.mood</code>.
     */
    public void setMood(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>journal_data.mood</code>.
     */
    public String getMood() {
        return (String) get(4);
    }

    /**
     * Setter for <code>journal_data.activity</code>.
     */
    public void setActivity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>journal_data.activity</code>.
     */
    public String getActivity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>journal_data.health</code>.
     */
    public void setHealth(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>journal_data.health</code>.
     */
    public String getHealth() {
        return (String) get(6);
    }

    /**
     * Setter for <code>journal_data.note</code>.
     */
    public void setNote(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>journal_data.note</code>.
     */
    public String getNote() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Integer, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JournalData.JOURNAL_DATA.NOTE_ID;
    }

    @Override
    public Field<String> field2() {
        return JournalData.JOURNAL_DATA.DATE;
    }

    @Override
    public Field<Integer> field3() {
        return JournalData.JOURNAL_DATA.DAY;
    }

    @Override
    public Field<String> field4() {
        return JournalData.JOURNAL_DATA.TITLE;
    }

    @Override
    public Field<String> field5() {
        return JournalData.JOURNAL_DATA.MOOD;
    }

    @Override
    public Field<String> field6() {
        return JournalData.JOURNAL_DATA.ACTIVITY;
    }

    @Override
    public Field<String> field7() {
        return JournalData.JOURNAL_DATA.HEALTH;
    }

    @Override
    public Field<String> field8() {
        return JournalData.JOURNAL_DATA.NOTE;
    }

    @Override
    public Integer component1() {
        return getNoteId();
    }

    @Override
    public String component2() {
        return getDate();
    }

    @Override
    public Integer component3() {
        return getDay();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getMood();
    }

    @Override
    public String component6() {
        return getActivity();
    }

    @Override
    public String component7() {
        return getHealth();
    }

    @Override
    public String component8() {
        return getNote();
    }

    @Override
    public Integer value1() {
        return getNoteId();
    }

    @Override
    public String value2() {
        return getDate();
    }

    @Override
    public Integer value3() {
        return getDay();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getMood();
    }

    @Override
    public String value6() {
        return getActivity();
    }

    @Override
    public String value7() {
        return getHealth();
    }

    @Override
    public String value8() {
        return getNote();
    }

    @Override
    public JournalDataRecord value1(Integer value) {
        setNoteId(value);
        return this;
    }

    @Override
    public JournalDataRecord value2(String value) {
        setDate(value);
        return this;
    }

    @Override
    public JournalDataRecord value3(Integer value) {
        setDay(value);
        return this;
    }

    @Override
    public JournalDataRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public JournalDataRecord value5(String value) {
        setMood(value);
        return this;
    }

    @Override
    public JournalDataRecord value6(String value) {
        setActivity(value);
        return this;
    }

    @Override
    public JournalDataRecord value7(String value) {
        setHealth(value);
        return this;
    }

    @Override
    public JournalDataRecord value8(String value) {
        setNote(value);
        return this;
    }

    @Override
    public JournalDataRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JournalDataRecord
     */
    public JournalDataRecord() {
        super(JournalData.JOURNAL_DATA);
    }

    /**
     * Create a detached, initialised JournalDataRecord
     */
    public JournalDataRecord(Integer noteId, String date, Integer day, String title, String mood, String activity, String health, String note) {
        super(JournalData.JOURNAL_DATA);

        setNoteId(noteId);
        setDate(date);
        setDay(day);
        setTitle(title);
        setMood(mood);
        setActivity(activity);
        setHealth(health);
        setNote(note);
    }
}
